lychee-crm:
  admin-firstname: admin
  admin-lastname: admin
  admin-username: adminus
  admin-password: maximus
  admin-sex: '""'
  admin-birthdate: '""'
mariadb:
  db-port: 3306
  db-root-password: lycheeOnTheGo
  db-user: lycheecrm
  db-password: lycheeOnTheGo
  db-name: lycheecrm



